global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
      monitor: 'prometheus-grafana-exporter'

# Alertmanager configuration
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093

# rule_files:
#   - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    metrics_path: /metrics
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'node'
    scrape_interval: 30s
    metrics_path: /metrics
    static_configs:
      - targets:
#           - 10.25.100.79:9182
          - 10.25.103.52:9100
#           - 10.25.103.7:9100

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - 10.25.103.52:8080

  - job_name: 'snmp'
    scrape_interval: 30s
    metrics_path: /snmp
    params:
      module: [if_mib_ifdescr]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmpexporter:9116
    static_configs:
      - targets:
          - 10.25.251.1
          - 192.168.130.1
          - 192.168.130.7
          - 192.168.130.8
          - 192.168.130.9
          - 192.168.130.10
          - 192.168.130.11
          - 192.168.130.12
          - 192.168.130.13
          - 192.168.130.14
          - 192.168.130.6
          - 192.168.130.31
          - 192.168.130.33
          - 192.168.130.30
          - 192.168.130.23
          - 192.168.130.26
          - 192.168.130.27
          - 192.168.130.21
          - 192.168.130.22
          - 192.168.130.20
          - 192.168.130.25
          - 192.168.130.29
          - 192.168.130.19
          - 192.168.130.18
          - 192.168.130.17
          - 192.168.130.16
          - 192.168.130.32
          - 192.168.130.28
          - 192.168.130.35


#  - job_name: 'checkpoint'
#    scrape_interval: 60s
#    metrics_path: '/index.txt'
#    static_configs:
#      - targets:
#          - 10.25.103.52:8008

  - job_name: 'pushgateway'
    scrape_interval: 60s
    metrics_path: '/metrics'
    honor_labels: true
    static_configs:
      - targets:
          - 10.25.103.52:9091

  - job_name: 'vmware'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 10.25.103.52:9512

  - job_name: 'telegraf'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 10.25.103.52:9273

  - job_name: 'influxdb'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 10.25.103.52:8086

  - job_name: 'loki'
    scrape_interval: 60s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 10.25.103.52:3100
