server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.25.103.52:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: localhost:1514
      labels:
        job: "syslog"
    relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'hostname'
      
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log